#!/usr/bin/env bash
# This script displays "Best School" 10 times using an until loop

a=1  # Initialize the counter

until [ $a -gt 10 ]
do
  echo "Best School"  # Print "Best School"
  ((a++))  # Increment the counter
done
